// Sample data for performance updates
export const performanceData = [
  {
    id: 1,
    class: "Class 5-B",
    subject: "Science",
    total_students: 70,
    pass: 64,
    fail: 6,
    students: [
      {
        id: 1,
        name: "Divyanshu Nagpal",
        attendance: 80,
        grades: 75,
        roll_no: 15,
        dob: "12/08/2002",
        class: 5,
        section: "B",
        blood_group: "O+",
        assignments: [
          {
            id: 1,
            name: "Assignment 1",
            max_grade: 10,
            secured_grade: 7,
          },
          {
            id: 2,
            name: "Assignment 2",
            max_grade: 10,
            secured_grade: 8,
          },
        ],
        remarks: [
          {
            id: 1,
            category: "Category 1",
            description: "Remark Description ...",
          },
          {
            id: 2,
            category: "Category 2",
            description: "Remark Description ...",
          },
          {
            id: 3,
            category: "Category 3",
            description: "Remark Description ...",
          },
        ],
        parent_info: {
          father_name: "Student's Father's Name",
          father_mob_no: "1234567890",
          mother_name: "Student's Mother's Name",
          mother_mob_no: "1234567890",
        },
      },
      {
        id: 1,
        name: "Divyanshu Nagpal",
        attendance: 80,
        grades: 75,
        roll_no: 15,
        dob: "12/08/2002",
        class: 5,
        section: "B",
        blood_group: "O+",
        assignments: [
          {
            id: 1,
            name: "Assignment 1",
            max_grade: 10,
            secured_grade: 7,
          },
          {
            id: 2,
            name: "Assignment 2",
            max_grade: 10,
            secured_grade: 8,
          },
        ],
        remarks: [
          {
            id: 1,
            category: "Category 1",
            description: "Remark Description ...",
          },
          {
            id: 2,
            category: "Category 2",
            description: "Remark Description ...",
          },
          {
            id: 3,
            category: "Category 3",
            description: "Remark Description ...",
          },
        ],
        parent_info: {
          father_name: "Student's Father's Name",
          father_mob_no: "1234567890",
          mother_name: "Student's Mother's Name",
          mother_mob_no: "1234567890",
        },
      },
    ],
  },
  {
    id: 2,
    class: "Class 5-B",
    subject: "Mathematics",
    total_students: 70,
    pass: 60,
    fail: 10,
    students: [
      {
        id: 3,
        name: "Student 3",
        attendance: 85,
        grades: 78,
        roll_no: 22,
        dob: "05/11/2002",
        blood_group: "A+",
        parent_info: {
          father_name: "Student 3's Father's Name",
          father_mob_no: "9876543210",
          mother_name: "Student 3's Mother's Name",
          mother_mob_no: "9876543210",
        },
      },
      {
        id: 4,
        name: "Student 4",
        attendance: 95,
        grades: 90,
      },
    ],
  },
  {
    id: 3,
    class: "Class 5-C",
    subject: "English",
    total_students: 75,
    pass: 70,
    fail: 5,
    students: [
      {
        id: 5,
        name: "Student 5",
        attendance: 88,
        grades: 82,
        roll_no: 18,
        dob: "20/04/2003",
        blood_group: "B+",
        parent_info: {
          father_name: "Student 5's Father's Name",
          father_mob_no: "8765432109",
          mother_name: "Student 5's Mother's Name",
          mother_mob_no: "8765432109",
        },
      },
      {
        id: 6,
        name: "Student 6",
        attendance: 92,
        grades: 88,
      },
    ],
  },
  {
    id: 4,
    class: "Class 5-C",
    subject: "Social Studies",
    total_students: 75,
    pass: 68,
    fail: 7,
    students: [
      {
        id: 7,
        name: "Student 7",
        attendance: 78,
        grades: 72,
        roll_no: 25,
        dob: "15/09/2002",
        blood_group: "AB+",
        parent_info: {
          father_name: "Student 7's Father's Name",
          father_mob_no: "7654321098",
          mother_name: "Student 7's Mother's Name",
          mother_mob_no: "7654321098",
        },
      },
      {
        id: 8,
        name: "Student 8",
        attendance: 85,
        grades: 80,
      },
    ],
  },
  {
    id: 5,
    class: "Class 5-A",
    subject: "History",
    total_students: 72,
    pass: 65,
    fail: 7,
    students: [
      {
        id: 11,
        name: "Student 11",
        attendance: 87,
        grades: 79,
        roll_no: 21,
        dob: "08/03/2003",
        blood_group: "A-",
        parent_info: {
          father_name: "Student 11's Father's Name",
          father_mob_no: "6543210987",
          mother_name: "Student 11's Mother's Name",
          mother_mob_no: "6543210987",
        },
      },
      {
        id: 12,
        name: "Student 12",
        attendance: 93,
        grades: 88,
      },
    ],
  },
  {
    id: 6,
    class: "Class 5-A",
    subject: "Physical Education",
    total_students: 72,
    pass: 68,
    fail: 4,
    students: [
      {
        id: 13,
        name: "Student 13",
        attendance: 82,
        grades: 75,
        roll_no: 19,
        dob: "25/11/2002",
        blood_group: "O-",
        parent_info: {
          father_name: "Student 13's Father's Name",
          father_mob_no: "5432109876",
          mother_name: "Student 13's Mother's Name",
          mother_mob_no: "5432109876",
        },
      },
      {
        id: 14,
        name: "Student 14",
        attendance: 91,
        grades: 82,
      },
    ],
  },
  {
    id: 7,
    class: "Class 5-C",
    subject: "Art",
    total_students: 75,
    pass: 70,
    fail: 5,
    students: [
      {
        id: 19,
        name: "Student 19",
        attendance: 88,
        grades: 82,
        roll_no: 28,
        dob: "14/05/2003",
        blood_group: "B-",
        parent_info: {
          father_name: "Student 19's Father's Name",
          father_mob_no: "8765432101",
          mother_name: "Student 19's Mother's Name",
          mother_mob_no: "8765432101",
        },
      },
      {
        id: 20,
        name: "Student 20",
        attendance: 92,
        grades: 88,
      },
    ],
  },
  {
    id: 8,
    class: "Class 5-D",
    subject: "Computer Science",
    total_students: 68,
    pass: 60,
    fail: 8,
    students: [
      {
        id: 21,
        name: "Student 21",
        attendance: 85,
        grades: 78,
        roll_no: 24,
        dob: "02/09/2002",
        blood_group: "AB-",
        parent_info: {
          father_name: "Student 21's Father's Name",
          father_mob_no: "7654321091",
          mother_name: "Student 21's Mother's Name",
          mother_mob_no: "7654321091",
        },
      },
      {
        id: 22,
        name: "Student 22",
        attendance: 95,
        grades: 90,
      },
    ],
  },
  {
    id: 9,
    class: "Class 5-D",
    subject: "Geography",
    total_students: 68,
    pass: 65,
    fail: 3,
    students: [
      {
        id: 23,
        name: "Student 23",
        attendance: 78,
        grades: 72,
        roll_no: 27,
        dob: "18/11/2002",
        blood_group: "A+",
        parent_info: {
          father_name: "Student 23's Father's Name",
          father_mob_no: "6543210981",
          mother_name: "Student 23's Mother's Name",
          mother_mob_no: "6543210981",
        },
      },
      {
        id: 24,
        name: "Student 24",
        attendance: 85,
        grades: 80,
      },
    ],
  },
  {
    id: 10,
    class: "Class 5-A",
    subject: "Music",
    total_students: 72,
    pass: 68,
    fail: 4,
    students: [
      {
        id: 25,
        name: "Student 25",
        attendance: 82,
        grades: 75,
        roll_no: 20,
        dob: "23/05/2003",
        blood_group: "O+",
        parent_info: {
          father_name: "Student 25's Father's Name",
          father_mob_no: "5432109871",
          mother_name: "Student 25's Mother's Name",
          mother_mob_no: "5432109871",
        },
      },
      {
        id: 26,
        name: "Student 26",
        attendance: 91,
        grades: 82,
      },
    ],
  },
];
