export const schoolWorkHistory = [
  {
    id: 1,
    assignment_name: "Assignment 1",
    group_name: "Group X",
    total_submissions: 30,
    submitted: 15,
    checked: 15,
    created: "12, Jan, 2022",
    due: "18, Jan, 2022",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eros mi, sagittis id lectus at, porttitor lobortis quam. Fusce id lacus tincidunt, vulputate quam nec, vestibulum dui. Sed convallis lacus a arcu porttitor, quis luctus nibh ultrices. Vestibulum faucibus neque vel turpis volutpat, ut placerat felis egestas. Nam convallis faucibus aliquet. Phasellus non aliquam sem. Aliquam iaculis turpis iaculis commodo vestibulum. Duis quis mi hendrerit, dictum est in, sollicitudin nibh. Morbi tempus, magna vel accumsan rutrum, dui nulla lobortis nibh, nec pellentesque sapien enim ac nisl.",
    student_submissions: [
      {
        id: 1,
        name: "Hehe 0",
        group_name: "Group X",
        file_name: "hardwork.txt",
        grades: 0,
      },
      {
        id: 2,
        name: "Hehe 1",
        file_name: "hardwork.txt",
        grades: 0,
      },
      {
        id: 3,
        name: "Hehe 2",
        file_name: "hardwork.txt",
        grades: 0,
      },
      {
        id: 4,
        name: "Hehe 3",
        file_name: "hardwork.txt",
        grades: 0,
      },
      {
        id: 5,
        name: "Hehe 4",
        file_name: "hardwork.txt",
        grades: 0,
      },
    ],
  },
  {
    id: 2,
    assignment_name: "Assignment 2",
    group_name: "Group Y",
    total_submissions: 25,
    submitted: 20,
    checked: 15,
    created: "15, Jan, 2022",
    due: "20, Jan, 2022",
  },
  {
    id: 3,
    assignment_name: "Assignment 3",
    group_name: "Group Z",
    total_submissions: 40,
    submitted: 30,
    checked: 10,
    created: "18, Jan, 2022",
    due: "25, Jan, 2022",
  },
  {
    id: 4,
    assignment_name: "Assignment 4",
    group_name: "Group X",
    total_submissions: 20,
    submitted: 10,
    checked: 10,
    created: "20, Jan, 2022",
    due: "28, Jan, 2022",
  },
  {
    id: 5,
    assignment_name: "Assignment 5",
    group_name: "Group Y",
    total_submissions: 35,
    submitted: 25,
    checked: 10,
    created: "22, Jan, 2022",
    due: "30, Jan, 2022",
  },
  {
    id: 6,
    assignment_name: "Assignment 6",
    group_name: "Group Z",
    total_submissions: 28,
    submitted: 15,
    checked: 13,
    created: "25, Jan, 2022",
    due: "5, Feb, 2022",
  },
  {
    id: 7,
    assignment_name: "Assignment 7",
    group_name: "Group X",
    total_submissions: 22,
    submitted: 20,
    checked: 2,
    created: "28, Jan, 2022",
    due: "10, Feb, 2022",
  },
  {
    id: 8,
    assignment_name: "Assignment 8",
    group_name: "Group Y",
    total_submissions: 18,
    submitted: 10,
    checked: 8,
    created: "1, Feb, 2022",
    due: "15, Feb, 2022",
  },
  {
    id: 9,
    assignment_name: "Assignment 9",
    group_name: "Group Z",
    total_submissions: 25,
    submitted: 15,
    checked: 10,
    created: "5, Feb, 2022",
    due: "18, Feb, 2022",
  },
  {
    id: 10,
    assignment_name: "Assignment 10",
    group_name: "Group X",
    total_submissions: 30,
    submitted: 25,
    checked: 5,
    created: "10, Feb, 2022",
    due: "22, Feb, 2022",
  },
];
