export const classData = [
  {
    id: 1,
    className: "5",
    section: "A",
    type: "One-on-One Meeting",
    date: "12 Jan, 2022",
    time_start: "5:15 PM",
    time_end: "6:15 PM",
    description: "Teaching Students about the Physics Topics and Doubt Session",
    join_link: "https://google.com/",
  },
  {
    id: 2,
    className: "6",
    section: "B",
    type: "Group Discussion",
    date: "15 Jan, 2022",
    time_start: "3:30 PM",
    time_end: "4:30 PM",
    description: "Discussing literature and analyzing texts as a group",
    join_link: "https://example.com/",
  },
  {
    id: 3,
    className: "7",
    section: "C",
    type: "Workshop",
    date: "18 Jan, 2022",
    time_start: "2:00 PM",
    time_end: "4:00 PM",
    description: "Hands-on workshop on programming concepts",
    join_link: "https://workshop-link.com/",
  },
  {
    id: 4,
    className: "8",
    section: "D",
    type: "Guest Lecture",
    date: "22 Jan, 2022",
    time_start: "10:00 AM",
    time_end: "12:00 PM",
    description: "Guest speaker discussing historical events",
    join_link: "https://guest-lecture.com/",
  },
  {
    id: 5,
    className: "9",
    section: "E",
    type: "Lab Session",
    date: "25 Jan, 2022",
    time_start: "1:30 PM",
    time_end: "3:30 PM",
    description: "Performing experiments in the chemistry lab",
    join_link: "https://lab-session-link.com/",
  },
  {
    id: 6,
    className: "10",
    section: "F",
    type: "Interactive Quiz",
    date: "28 Jan, 2022",
    time_start: "4:00 PM",
    time_end: "5:00 PM",
    description: "Engaging quiz to test knowledge on current affairs",
    join_link: "https://quiz-join.com/",
  },
  {
    id: 7,
    className: "11",
    section: "G",
    type: "Debate",
    date: "1 Feb, 2022",
    time_start: "6:00 PM",
    time_end: "8:00 PM",
    description: "Participate in a debate on social issues",
    join_link: "https://debate-link.com/",
  },
  {
    id: 8,
    className: "12",
    section: "H",
    type: "Peer Review Session",
    date: "5 Feb, 2022",
    time_start: "11:00 AM",
    time_end: "12:30 PM",
    description: "Reviewing and providing feedback on peer projects",
    join_link: "https://peer-review.com/",
  },
  {
    id: 9,
    className: "13",
    section: "I",
    type: "Guest Workshop",
    date: "8 Feb, 2022",
    time_start: "2:30 PM",
    time_end: "4:30 PM",
    description: "Special workshop by industry experts",
    join_link: "https://guest-workshop.com/",
  },
  {
    id: 10,
    className: "14",
    section: "J",
    type: "Study Group",
    date: "12 Feb, 2022",
    time_start: "7:00 PM",
    time_end: "9:00 PM",
    description: "Collaborative study session for upcoming exams",
    join_link: "https://study-group-link.com/",
  },
];
