export const markAttendanceData = [
  // Sample 1
  {
    id: 1,
    class: "5",
    section: "B",
    subject: "Science",
    marked: false,
    students: [
      { id: 1, roll_no: 1, name: "Divyanshu Nagpal", present: true },
      { id: 2, roll_no: 2, name: "Aisha Patel", present: false },
      { id: 3, roll_no: 3, name: "Ravi Singh", present: true },
      { id: 4, roll_no: 4, name: "Priya Sharma", present: false },
      { id: 5, roll_no: 5, name: "Kiran Kumar", present: true },
      { id: 6, roll_no: 6, name: "Sara Khan", present: true },
      { id: 7, roll_no: 7, name: "Rahul Mehta", present: false },
      { id: 8, roll_no: 8, name: "Ananya Verma", present: true },
      { id: 9, roll_no: 9, name: "Vikram Singh", present: false },
      { id: 10, roll_no: 10, name: "Neha Sharma", present: true },
    ],
  },
  // Sample 2
  {
    id: 2,
    class: "6",
    section: "A",
    subject: "Mathematics",
    marked: false,
    students: [
      { id: 11, roll_no: 1, name: "Aditya Patel", present: true },
      { id: 12, roll_no: 2, name: "Anjali Gupta", present: false },
      { id: 13, roll_no: 3, name: "Rahul Kapoor", present: true },
      { id: 14, roll_no: 4, name: "Pooja Verma", present: false },
      { id: 15, roll_no: 5, name: "Rajeev Kumar", present: true },
      { id: 16, roll_no: 6, name: "Shweta Singh", present: true },
      { id: 17, roll_no: 7, name: "Ajay Mehta", present: false },
      { id: 18, roll_no: 8, name: "Sanya Verma", present: true },
      { id: 19, roll_no: 9, name: "Vivek Singh", present: false },
      { id: 20, roll_no: 10, name: "Anita Sharma", present: true },
    ],
  },
  // Sample 3
  {
    id: 3,
    class: "7",
    section: "C",
    subject: "English",
    marked: false,
    students: [
      { id: 21, roll_no: 1, name: "Arjun Patel", present: true },
      { id: 22, roll_no: 2, name: "Nisha Gupta", present: false },
      { id: 23, roll_no: 3, name: "Karan Kapoor", present: true },
      { id: 24, roll_no: 4, name: "Simran Verma", present: false },
      { id: 25, roll_no: 5, name: "Amit Kumar", present: true },
      { id: 26, roll_no: 6, name: "Tanvi Singh", present: true },
      { id: 27, roll_no: 7, name: "Raj Mehta", present: false },
      { id: 28, roll_no: 8, name: "Ankit Verma", present: true },
      { id: 29, roll_no: 9, name: "Neha Singh", present: false },
      { id: 30, roll_no: 10, name: "Manisha Sharma", present: true },
    ],
  },
  // Sample 4
  {
    id: 4,
    class: "8",
    section: "B",
    subject: "Social Studies",
    marked: false,
    students: [
      { id: 31, roll_no: 1, name: "Varun Patel", present: true },
      { id: 32, roll_no: 2, name: "Ananya Gupta", present: false },
      { id: 33, roll_no: 3, name: "Nitin Kapoor", present: true },
      { id: 34, roll_no: 4, name: "Sonia Verma", present: false },
      { id: 35, roll_no: 5, name: "Rohit Kumar", present: true },
      { id: 36, roll_no: 6, name: "Deepa Singh", present: true },
      { id: 37, roll_no: 7, name: "Amit Mehta", present: false },
      { id: 38, roll_no: 8, name: "Sneha Verma", present: true },
      { id: 39, roll_no: 9, name: "Vikas Singh", present: false },
      { id: 40, roll_no: 10, name: "Preeti Sharma", present: true },
    ],
  },
  // Sample 5
  {
    id: 5,
    class: "9",
    section: "A",
    subject: "Physics",
    marked: false,
    students: [
      { id: 41, roll_no: 1, name: "Rahul Patel", present: true },
      { id: 42, roll_no: 2, name: "Komal Gupta", present: false },
      { id: 43, roll_no: 3, name: "Sunny Kapoor", present: true },
      { id: 44, roll_no: 4, name: "Alisha Verma", present: false },
      { id: 45, roll_no: 5, name: "Vijay Kumar", present: true },
      { id: 46, roll_no: 6, name: "Shreya Singh", present: true },
      { id: 47, roll_no: 7, name: "Arun Mehta", present: false },
      { id: 48, roll_no: 8, name: "Anjali Verma", present: true },
      { id: 49, roll_no: 9, name: "Ravi Singh", present: false },
      { id: 50, roll_no: 10, name: "Suman Sharma", present: true },
    ],
  },
];
