export const timetableData = [
  {
    id: 1,
    time: "9:00 AM",
    class: "5",
    section: "B",
    subject: "Science",
    course_code: "C-145",
    teacher: "Mrs. Rajni Mehta",
    attendance: true,
    break: false,
  },
  {
    id: 2,
    time: "10:00 AM",
    class: "5",
    section: "B",
    subject: "Math",
    course_code: "M-201",
    teacher: "Mrs. Rajni Mehta",
    attendance: true,
    break: false,
  },
  {
    id: 3,
    time: "11:00 AM",
    class: "5",
    section: "B",
    subject: "English",
    course_code: "E-102",
    teacher: "Mrs. Rajni Mehta",
    attendance: false,
    break: false,
  },
  {
    id: 4,
    time: "12:00 PM",
    class: "", // Lunch Break
    section: "",
    subject: "Lunch",
    course_code: "",
    attendance: false,
    break: true,
  },
  {
    id: 5,
    time: "1:00 PM",
    class: "5",
    section: "B",
    subject: "Social Studies",
    course_code: "S-301",
    teacher: "Mrs. Rajni Mehta",
    attendance: false,
    break: false,
  },
];
